"""Generate the rights-cleared BridgeTrend OpenCV demo fixture pack."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import numpy as np

PACK_VERSION = "1.0.0"
CASE_IDS = (
    "exact_match",
    "close_substitute",
    "visual_style",
    "low_quality_recovery",
    "ambiguous_candidates",
    "unsupported_match",
)


def generate_demo_fixture_pack(output_dir: str | Path) -> dict[str, Any]:
    """Create 24 deterministic product-like images and their case manifest."""

    import cv2

    output_dir = Path(output_dir)
    image_root = output_dir / "images"
    image_root.mkdir(parents=True, exist_ok=True)

    cases: list[dict[str, Any]] = []
    contact_rows: list[np.ndarray] = []
    written_images: list[Path] = []
    for case_index, case_id in enumerate(CASE_IDS):
        case_dir = image_root / case_id
        case_dir.mkdir(parents=True, exist_ok=True)
        images = _render_case(case_id)
        relative_paths: list[str] = []
        for image_index, image in enumerate(images):
            name = "query.png" if image_index == 0 else f"evidence_{image_index}.png"
            path = case_dir / name
            if not cv2.imwrite(str(path), image):
                raise RuntimeError(f"OpenCV could not write fixture image: {path}")
            written_images.append(path)
            relative_paths.append(str(path.relative_to(output_dir)))
        cases.append(_case_manifest(case_id, relative_paths, case_index))
        contact_rows.append(np.concatenate([_labeled(item, case_id) for item in images], axis=1))

    contact_sheet = np.concatenate(contact_rows, axis=0)
    contact_path = output_dir / "contact_sheet.png"
    if not cv2.imwrite(str(contact_path), contact_sheet):
        raise RuntimeError(f"OpenCV could not write contact sheet: {contact_path}")

    checksum_lines = [
        f"{hashlib.sha256(path.read_bytes()).hexdigest()}  {path.relative_to(output_dir)}"
        for path in sorted(written_images)
    ]
    (output_dir / "SHA256SUMS").write_text(
        "\n".join(checksum_lines) + "\n",
        encoding="utf-8",
    )

    payload: dict[str, Any] = {
        "pack_version": PACK_VERSION,
        "license": "CC0-1.0",
        "provenance": "Deterministically generated by BridgeTrend; no external images.",
        "image_count": len(CASE_IDS) * 4,
        "cases": cases,
    }
    (output_dir / "cases.json").write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return payload


def _render_case(case_id: str) -> tuple[np.ndarray, ...]:
    if case_id == "exact_match":
        base = _product("bag", (42, 92, 220), "BT-01", 101, pattern="grid")
        return (
            base,
            _transform(base, angle=5.0, shift=(7, -4), brightness=1.04),
            _transform(base, angle=-7.0, shift=(-8, 5), brightness=0.92),
            _product("figure", (180, 75, 55), "NX-80", 102, pattern="dots"),
        )
    if case_id == "close_substitute":
        query = _product("bag", (55, 145, 220), "CITY", 201, pattern="grid")
        return (
            query,
            _product("bag", (58, 150, 218), "CITY+", 202, pattern="grid", variant=1),
            _product("bag", (70, 160, 210), "CITI", 203, pattern="grid", variant=2),
            _product("bottle", (55, 145, 220), "CITY", 204, pattern="grid"),
        )
    if case_id == "visual_style":
        query = _product("bag", (190, 70, 190), "NEON", 301, pattern="zigzag")
        return (
            query,
            _product("figure", (190, 70, 190), "NEON", 302, pattern="zigzag"),
            _product("bottle", (190, 70, 190), "NEON", 303, pattern="zigzag"),
            _product("shoe", (50, 150, 65), "PLAIN", 304, pattern="dots"),
        )
    if case_id == "low_quality_recovery":
        clean = _product("bottle", (35, 165, 120), "PURE", 401, pattern="grid")
        degraded = _degrade(clean)
        return (
            degraded,
            clean,
            _transform(clean, angle=4.0, shift=(5, 2), brightness=1.03),
            _product("bottle", (170, 70, 45), "OTHER", 402, pattern="dots"),
        )
    if case_id == "ambiguous_candidates":
        query = _product("shoe", (225, 110, 35), "RUN-A", 501, pattern="stripes")
        return (
            query,
            _product("shoe", (225, 110, 35), "RUN-A", 502, pattern="stripes", variant=1),
            _product("shoe", (220, 115, 40), "RUN-B", 503, pattern="stripes", variant=2),
            _product("shoe", (215, 120, 45), "RUN-C", 504, pattern="stripes", variant=3),
        )
    if case_id == "unsupported_match":
        return (
            _product("watch", (45, 60, 75), "TIME", 601, pattern="grid"),
            _product("mug", (210, 110, 40), "CUP", 602, pattern="dots"),
            _product("lamp", (60, 175, 195), "LAMP", 603, pattern="zigzag"),
            _product("bag", (165, 60, 175), "BAG", 604, pattern="stripes"),
        )
    raise ValueError(f"unknown demo case: {case_id}")


def _case_manifest(
    case_id: str,
    images: list[str],
    case_index: int,
) -> dict[str, Any]:
    expected = {
        "exact_match": "accept",
        "close_substitute": "human_review",
        "visual_style": "human_review",
        "low_quality_recovery": "accept",
        "ambiguous_candidates": "human_review",
        "unsupported_match": "reject",
    }[case_id]
    labels = {
        "exact_match": "L3_exact",
        "close_substitute": "L2_substitute",
        "visual_style": "L1_style",
        "low_quality_recovery": "L3_after_better_image",
        "ambiguous_candidates": "L2_ambiguous",
        "unsupported_match": "L0_unsupported",
    }
    initial = {
        "top_similarity": 0.90,
        "runner_up_similarity": 0.78,
        "quality_score": 0.80,
        "evidence_count": 1,
        "source_diversity": 1,
    }
    if case_id == "exact_match":
        initial.update(top_similarity=0.94, runner_up_similarity=0.70)
        retrieval = (0.98, 0.94, 0.58)
    elif case_id == "close_substitute":
        initial.update(top_similarity=0.88, runner_up_similarity=0.78)
        retrieval = (0.78, 0.76, 0.68)
    elif case_id == "visual_style":
        initial.update(top_similarity=0.86, runner_up_similarity=0.77)
        retrieval = (0.88, 0.86, 0.60)
    elif case_id == "low_quality_recovery":
        initial.update(top_similarity=0.91, runner_up_similarity=0.70, quality_score=0.40)
        retrieval = (0.95, 0.97, 0.58)
    elif case_id == "ambiguous_candidates":
        initial.update(top_similarity=0.91, runner_up_similarity=0.89)
        retrieval = (0.94, 0.93, 0.91)
    else:
        initial.update(top_similarity=0.66, runner_up_similarity=0.56)
        retrieval = (0.58, 0.53, 0.49)

    observations: list[dict[str, Any]] = []
    for index in range(1, 4):
        candidate_id = f"{case_id}-candidate-{index}"
        if case_id in {"exact_match", "low_quality_recovery"} and index < 3:
            candidate_id = f"{case_id}-target"
        roles = ["additional_product_image", "independent_marketplace_source"]
        observation: dict[str, Any] = {
            "evidence_id": f"{case_id}-evidence-{index}",
            "candidate_id": candidate_id,
            "image_path": images[index],
            "source": f"synthetic_cn_source_{case_index + 1}_{index}",
            "market": "CN",
            "retrieval_similarity": retrieval[index - 1],
            "evidence_roles": roles,
        }
        if case_id == "low_quality_recovery" and index == 2:
            observation["query_image_path"] = images[1]
            observation["evidence_roles"] = roles + ["higher_quality_image"]
        observations.append(observation)

    return {
        "case_id": case_id,
        "label": labels[case_id],
        "query_image": images[0],
        "query_source": f"synthetic_us_source_{case_index + 1}",
        "initial_evidence": initial,
        "max_acquisitions": 2,
        "observations": observations,
        "expected_decision": expected,
    }


def _product(
    shape: str,
    color: tuple[int, int, int],
    code: str,
    seed: int,
    *,
    pattern: str,
    variant: int = 0,
) -> np.ndarray:
    import cv2

    rng = np.random.default_rng(seed)
    image = np.full((384, 384, 3), 246, dtype=np.uint8)
    for _ in range(28):
        center = tuple(int(value) for value in rng.integers(10, 374, size=2))
        shade = int(rng.integers(224, 242))
        cv2.circle(image, center, int(rng.integers(1, 4)), (shade,) * 3, -1)
    cv2.ellipse(image, (192, 318), (105, 18), 0, 0, 360, (214, 218, 224), -1)

    mask = np.zeros((384, 384), dtype=np.uint8)
    if shape == "bag":
        cv2.rectangle(mask, (100, 135), (284, 295), 255, -1)
        cv2.ellipse(mask, (192, 145), (72 - variant * 4, 76), 180, 0, 180, 255, 18)
    elif shape == "figure":
        cv2.circle(mask, (192, 135), 65, 255, -1)
        cv2.ellipse(mask, (192, 245), (78, 92), 0, 0, 360, 255, -1)
    elif shape == "bottle":
        cv2.rectangle(mask, (143, 115), (241, 304), 255, -1)
        cv2.rectangle(mask, (166, 82), (218, 125), 255, -1)
    elif shape == "shoe":
        points = np.array([[78, 245], [150, 180], [225, 218], [306, 244], [318, 286], [88, 286]])
        cv2.fillPoly(mask, [points.astype(np.int32)], 255)
    elif shape == "watch":
        cv2.rectangle(mask, (165, 55), (219, 329), 255, -1)
        cv2.circle(mask, (192, 192), 82, 255, -1)
    elif shape == "mug":
        cv2.rectangle(mask, (112, 125), (257, 294), 255, -1)
        cv2.ellipse(mask, (263, 205), (48, 61), 0, 270, 90, 255, 20)
    elif shape == "lamp":
        cv2.fillPoly(mask, [np.array([[110, 215], [165, 95], [219, 95], [274, 215]])], 255)
        cv2.rectangle(mask, (179, 210), (205, 306), 255, -1)
        cv2.rectangle(mask, (135, 300), (249, 322), 255, -1)
    else:
        raise ValueError(f"unknown product shape: {shape}")

    product = np.zeros_like(image)
    product[:, :] = color
    _draw_pattern(product, mask, pattern, variant)
    product = cv2.bitwise_and(product, product, mask=mask)
    background = cv2.bitwise_and(image, image, mask=cv2.bitwise_not(mask))
    image = cv2.add(background, product)
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    cv2.drawContours(image, contours, -1, (35, 39, 46), 4)
    cv2.putText(image, code, (132, 205), cv2.FONT_HERSHEY_DUPLEX, 0.75, (250, 250, 250), 2, cv2.LINE_AA)
    cv2.putText(image, "BRIDGETREND", (112, 345), cv2.FONT_HERSHEY_SIMPLEX, 0.45, (82, 88, 96), 1, cv2.LINE_AA)
    return image


def _draw_pattern(
    product: np.ndarray,
    mask: np.ndarray,
    pattern: str,
    variant: int,
) -> None:
    import cv2

    ink = (235, 235, 235)
    overlay = np.zeros_like(product)
    if pattern == "grid":
        for offset in range(80 + variant * 3, 310, 30):
            cv2.line(overlay, (offset, 80), (offset, 310), ink, 3)
            cv2.line(overlay, (70, offset), (310, offset), ink, 3)
    elif pattern == "dots":
        for x in range(100, 300, 35):
            for y in range(100, 300, 35):
                cv2.circle(overlay, (x, y), 7 + variant, ink, -1)
    elif pattern == "zigzag":
        for y in range(115, 300, 35):
            points = np.array([[85, y], [135, y - 16], [185, y], [235, y - 16], [295, y]])
            cv2.polylines(overlay, [points], False, ink, 4)
    elif pattern == "stripes":
        for offset in range(-100, 420, 32):
            cv2.line(overlay, (offset, 330), (offset + 220, 80), ink, 5)
    else:
        raise ValueError(f"unknown pattern: {pattern}")
    pattern_mask = cv2.bitwise_and(mask, cv2.cvtColor(overlay, cv2.COLOR_BGR2GRAY))
    product[pattern_mask > 0] = overlay[pattern_mask > 0]


def _transform(
    image: np.ndarray,
    *,
    angle: float,
    shift: tuple[int, int],
    brightness: float,
) -> np.ndarray:
    import cv2

    matrix = cv2.getRotationMatrix2D((192, 192), angle, 0.96)
    matrix[:, 2] += shift
    transformed = cv2.warpAffine(
        image,
        matrix,
        (384, 384),
        borderMode=cv2.BORDER_CONSTANT,
        borderValue=(246, 246, 246),
    )
    return np.clip(transformed.astype(np.float32) * brightness, 0, 255).astype(np.uint8)


def _degrade(image: np.ndarray) -> np.ndarray:
    import cv2

    tiny = cv2.resize(image, (64, 64), interpolation=cv2.INTER_AREA)
    degraded = cv2.resize(tiny, (384, 384), interpolation=cv2.INTER_LINEAR)
    degraded = cv2.GaussianBlur(degraded, (31, 31), 11)
    return np.clip(degraded.astype(np.float32) * 0.38, 0, 255).astype(np.uint8)


def _labeled(image: np.ndarray, case_id: str) -> np.ndarray:
    import cv2

    rendered = cv2.resize(image, (192, 192), interpolation=cv2.INTER_AREA)
    cv2.rectangle(rendered, (0, 166), (192, 192), (20, 24, 32), -1)
    cv2.putText(rendered, case_id[:22], (6, 184), cv2.FONT_HERSHEY_SIMPLEX, 0.38, (245, 247, 250), 1, cv2.LINE_AA)
    return rendered
